import { PortfolioContent, Language } from './types';

export const portfolioData: Record<Language, PortfolioContent> = {
  es: {
    nav: {
      items: [
        { label: 'Sobre Mí', href: '#about' },
        { label: 'Proyectos', href: '#projects' },
        { label: 'Contacto', href: '#contact' },
      ],
      contactCta: 'Contacto',
    },
    hero: {
      greeting: 'Hola, soy',
      name: 'Juan David Quintero',
      headline: 'Software Engineer & Builder.',
      subtitle:
        'Transformo problemas de negocio en arquitecturas limpias, modulares y listas para producción.',
      badge: 'Software Engineer',
      primaryCta: {
        text: 'Ver Proyectos',
        targetId: 'projects',
      },
      secondaryCta: {
        text: 'Descargar CV',
        url: '/HV_JUAN_DAVID_QUINTERO_ES.pdf',
      },
      socials: [
        {
          name: 'LinkedIn',
          url: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
          icon: 'linkedin',
          ariaLabel: 'Perfil de LinkedIn de Juan David Quintero',
        },
        {
          name: 'Email',
          url: 'mailto:juandavidquintero49@gmail.com',
          icon: 'email',
          ariaLabel: 'Enviar correo a Juan David Quintero',
        },
      ],
      profileAlt: 'Juan David Quintero Peña frente a la Estatua de la Libertad, NYC',
      sidebarItems: [
        { icon: 'code', label: 'Software Engineer' },
        { icon: 'graduation', label: 'Icesi University' },
        { icon: 'map', label: 'Cali, Colombia' },
        { icon: 'typescript', label: 'TypeScript' },
        { icon: 'puzzle', label: 'Solving Complex Problems' },
        { icon: 'rocket', label: 'Building Scalable Apps' },
        { icon: 'brain', label: 'AI & Automation' },
      ],
      profileCardName: 'Juan David Quintero',
      profileCardRole: 'Software Engineer & Builder',
    },
    about: {
      title: 'Sobre Mí',
      manifestoParagraphs: [
        'No concibo el desarrollo de software como una simple transcripción de requerimientos a código.',
        'Mi enfoque está en entender a fondo el problema de negocio, anticipar los cuellos de botella de escalabilidad y diseñar sistemas que reduzcan la fricción operativa.',
        'Me especializo en el ecosistema TypeScript (Next.js 15, NestJS), backend en Java y bases de datos relacionales, integrando flujos de inteligencia artificial donde realmente aportan eficiencia tangible.',
      ],
    },
    featuredProjects: {
      chip: 'Proyectos Destacados',
      headlineFirst: 'Arquitectura para escalar.',
      headlineSecond: 'Diseñada para impacto real.',
      subtitle:
        'Sistemas en producción respaldados por aislamiento estricto de datos, resiliencia distribuida y automatización pragmática con IA.',
      links: {
        viewProject: 'Detalles Técnicos',
        viewCode: 'Repositorio',
        liveDemo: 'Demo en Vivo',
      },
      projects: [
        {
          id: 'b2b-saas',
          category: 'ARQUITECTURA & SAAS',
          title: 'B2B Multi-Tenant SaaS Automation Platform',
          tagline:
            'Plataforma modular de automatización operativa y gestión empresarial sin dispersión de código.',
          description:
            'Diseñada para resolver la variabilidad de integraciones en empresas B2B. Implementé aislamiento estricto de clientes mediante middleware dinámico y políticas Row Level Security (RLS) en PostgreSQL. Estructuré patrones Adapter y Strategy que permiten conectar desde APIs REST hasta cargas SFTP personalizadas sin tocar el código base de los módulos.',
          stack: ['Next.js 15', 'Supabase', 'PostgreSQL', 'Tailwind CSS', 'Adapter Pattern'],
          metric:
            'Aislamiento 100% garantizado a nivel de base de datos y despliegues modulares controlados por configuración JSONB.',
          metricLabel: 'Impacto en Producción',
          demoUrl: '#',
          githubUrl: '#',
        },
        {
          id: 'real-estate-crm',
          category: 'PRODUCTO EN PRODUCCIÓN & IA',
          title: 'Plataforma Inmobiliaria y CRM Automatizado',
          tagline:
            'Solución comercial integral con precalificación automatizada de prospectos y sincronización publicitaria.',
          description:
            'Desarrollo de portal web y CRM interno para centralizar la prospección y catálogo de inmuebles. Orquesté un agente conversacional en n8n que interactúa de manera natural para precalificar clientes (presupuesto, ubicación, método de pago) antes de pasarlos a un asesor, complementado con generación de contenido asistida por IA y publicación hacia Meta.',
          stack: ['Next.js 15', 'Supabase', 'n8n', 'Meta Graph API', 'Agentes IA'],
          metric:
            'Ahorro de ~16 horas semanales en tareas operativas manuales y más de 140 clientes potenciales calificados procesados.',
          metricLabel: 'Eficiencia Operativa',
          demoUrl: '#',
          githubUrl: '#',
        },
        {
          id: 'distributed-voting',
          category: 'SISTEMAS DISTRIBUIDOS & RESILIENCIA',
          title: 'High-Availability Distributed Voting Infrastructure',
          tagline:
            'Arquitectura distribuida tolerante a fallos para procesamiento seguro de votaciones masivas.',
          description:
            'Infraestructura diseñada en Java 11 comunicada a través de middleware ZeroC ICE sobre servidores institucionales independientes. Implementé el patrón Reliable Messaging con persistencia transaccional y reintentos automáticos con UUID único para impedir pérdidas o duplicaciones de votos durante interrupciones en los enlaces.',
          stack: ['Java 11', 'ZeroC ICE', 'Reliable Messaging', 'Sistemas Distribuidos', 'JUnit'],
          metric:
            'Cero pérdida de registros bajo pruebas de estrés de +100.000 votos y recuperación automática tras caídas forzadas de red de 30 segundos.',
          metricLabel: 'Tolerancia a Fallos',
          demoUrl: '#',
          githubUrl: '#',
        },
        {
          id: 'intelligent-electives',
          category: 'IA APLICADA & RECUPERACIÓN HÍBRIDA',
          title: 'Intelligent Electives Navigation Assistant',
          tagline:
            'Motor conversacional con búsqueda semántica y filtros relacionales para catálogo universitario.',
          description:
            'Diseñado para solucionar las limitaciones de los sistemas RAG puramente vectoriales ante restricciones exactas. Combina embeddings semánticos en pgvector con búsquedas textuales SQL para resolver consultas que cruzan intenciones subjetivas de estudiantes con horarios y prerrequisitos estrictos de más de 120 cursos.',
          stack: ['Python', 'n8n', 'Supabase (pgvector)', 'Hybrid Search', 'LLMs'],
          metric:
            'Precisión consistente en consultas combinadas (tema de interés + restricción de día/hora).',
          metricLabel: 'Precisión RAG Híbrido',
          demoUrl: '#',
          githubUrl: '#',
        },
      ],
    },
    otherProjects: {
      chip: 'Más Proyectos',
      headlineFirst: 'Otros',
      headlineSecond: 'Proyectos & Experimentos',
      subtitle: 'Explora una colección de soluciones innovadoras y arquitecturas adicionales en las que he trabajado.',
      projects: [
        {
          id: 'hr-agile-platform',
          category: 'Full-Stack & CI/CD',
          title: 'Enterprise HR Agile Platform',
          tagline: 'Plataforma colaborativa para optimización de flujos de reclutamiento y seguimiento de candidatos.',
          description: 'Sistema integral con backend en Spring Boot y frontend reactivo en Next.js. Diseñé tableros interactivos tipo Kanban para gestionar pipelines dinámicos de selección con autenticación basada en roles. Configuré la integración continua mediante pipelines automatizados en Jenkins para pruebas y despliegue.',
          stack: ['Spring Boot', 'Next.js', 'PostgreSQL', 'Jenkins', 'REST APIs', 'Docker'],
          impact: 'Liderazgo técnico como Scrum Master para un equipo de 8 ingenieros, reduciendo fricciones en entregas quincenales y automatizando pruebas de regresión.',
          image: 'https://images.unsplash.com/photo-1542626991-cbc4e32524cc?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Arquitectura',
          actionUrl: '#',
          actionSecondaryText: 'Repositorio GitHub',
          actionSecondaryUrl: '#',
        },
        {
          id: 'consulting-management',
          category: 'Enterprise Architecture',
          title: 'Corporate Consulting Management System',
          tagline: 'Plataforma centralizada para gestión contractual, presupuestal y seguimiento de consultorías institucionales.',
          description: 'Aplicación empresarial para digitalizar el ciclo de vida de consultorías de alto valor de la Universidad Icesi. Integré autenticación corporativa con Microsoft Azure AD y modelé permisos jerárquicos multi-nivel para coordinadores, consultores y líderes de proyecto.',
          stack: ['Next.js 15', 'NestJS', 'TypeScript', 'PostgreSQL', 'Azure AD'],
          impact: 'Trazabilidad integral en tiempo real de flujos de aprobación y contratos financieros, eliminando la dispersión de información en hojas de cálculo.',
          image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
          actionText: 'Caso de Estudio',
          actionUrl: '#',
          actionSecondaryText: 'Documentación Técnica',
          actionSecondaryUrl: '#',
        },
        {
          id: 'resilient-microservices',
          category: 'DevOps & Cloud Engineering',
          title: 'Resilient Microservices CI/CD Pipeline',
          tagline: 'Entorno orquestado de despliegue continuo y validación de carga para arquitecturas desacopladas.',
          description: 'Pipeline automatizado en Jenkins que gestiona el ciclo de vida de múltiples microservicios contenerizados con Docker. Implementé despliegues multi-namespace en Kubernetes y simulé escenarios de estrés concurrente y latencia mediante pruebas automatizadas con Locust.',
          stack: ['Docker', 'Kubernetes', 'Jenkins', 'Redis', 'Kafka', 'Locust', 'Linux'],
          impact: 'Automatización del 100% de los pasos de prueba y despliegue local, asegurando rollback ante fallos en tests de integración.',
          image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Configuración Docker/K8s',
          actionUrl: '#',
        },
        {
          id: 'dynamic-habits-insurtech',
          category: 'Fintech & Hackathon',
          title: 'Dynamic Habits-Based Insurance Engine',
          tagline: 'Prototipo funcional para cotización adaptativa de pólizas basado en perfilamiento de hábitos.',
          description: 'Motor de cálculo y plataforma interactiva desarrollada contrarreloj durante la competencia Global Hack 2025. Diseñé la lógica para procesar métricas de estilo de vida del usuario y ajustar dinámicamente las primas de seguros en tiempo real mediante interfaces ágiles.',
          stack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'REST APIs'],
          impact: 'Reconocimiento Top 3 a nivel interinstitucional (Global Seguros & Design Factory Javeriana) entre decenas de propuestas.',
          image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Demo Conceptual',
          actionUrl: '#',
          actionSecondaryText: 'Resumen del Reto',
          actionSecondaryUrl: '#',
        },
        {
          id: 'cross-platform-mobile',
          category: 'Mobile Development',
          title: 'Cross-Platform Reactive Mobile App',
          tagline: 'Aplicación para dispositivos móviles con gestión reactiva de estado y componentes nativos.',
          description: 'Desarrollo de interfaces móviles fluidas y adaptativas para iOS y Android utilizando Flutter. Implementé patrones de arquitectura desacoplada para el consumo de endpoints REST y persistencia local de datos en caché offline.',
          stack: ['Flutter', 'Dart', 'REST APIs', 'SQLite', 'Hive'],
          impact: 'Arquitectura modular con cobertura de componentes reutilizables y sincronización asíncrona de datos.',
          image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Demo Móvil',
          actionUrl: '#',
          actionSecondaryText: 'Código Fuente',
          actionSecondaryUrl: '#',
        },
        {
          id: 'custom-algorithmic',
          category: 'Backend & Core Algorithms',
          title: 'Custom Algorithmic & Backend Solutions',
          tagline: 'Módulos de procesamiento algorítmico, lógica transaccional y optimización de estructuras de datos.',
          description: 'Desarrollo de soluciones a la medida para clientes independientes centradas en resolver problemas computacionales de alta complejidad. Incluye implementación y refactorización de grafos, árboles balanceados, colas de prioridad y optimización de consultas en Java.',
          stack: ['Java', 'JUnit', 'Algoritmos', 'Estructuras de datos avanzadas', 'Git'],
          impact: 'Reducción en tiempos de ejecución de algoritmos heredados y 100% de cumplimiento en especificaciones técnicas de clientes independientes.',
          image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Ejemplos de Lógica',
          actionUrl: '#',
        }
      ]
    },
    workExperience: {
      chip: 'Experiencia Laboral',
      headlineFirst: 'Trayectoria Profesional &',
      headlineSecond: 'Roles en Producción',
      subtitle: 'Historial de desarrollo de software, arquitectura de sistemas, automatización y liderazgo operativo.',
      entries: [
        {
          id: 'carolina-pena',
          period: 'Mar 2026 – Presente',
          current: true,
          role: 'Ingeniero de Software Full-Stack & Automatización',
          company: 'Carolina Peña Inmobiliaria',
          location: 'Cali, Colombia',
          locationKind: 'Remoto',
          employmentType: 'Profesional Independiente',
          shortDescription: 'Desarrollo de plataforma web y CRM a medida con Next.js 15 y Supabase, con sincronización publicitaria y flujos en n8n.',
          bullets: [
            'Diseño e implementación de la arquitectura completa del portal inmobiliario y CRM a medida sobre Next.js 15 y PostgreSQL (Supabase).',
            'Automatización de publicaciones mediante Meta Graph API y flujo de calificación de prospectos con n8n, procesando +140 leads y ahorrando ~16h/semana de gestión manual.',
          ],
          logo: '/logo-carolina-pena-white.jpeg',
          accentColor: '#dcb991',
        },
        {
          id: 'camp-romaca',
          period: 'Jun 2026 – Ago 2026',
          role: 'High Ropes Instructor & Camp Counselor',
          company: 'Camp Romaca',
          location: 'Becket, MA, EE. UU.',
          locationKind: 'Internacional',
          employmentType: 'Inmersión Internacional',
          shortDescription: 'Instrucción técnica y liderazgo de seguridad en circuitos de cuerdas altas en entorno 100% en inglés.',
          bullets: [
            'Inspección técnica diaria y control de protocolos de seguridad en circuitos de cuerdas altas bajo normativa internacional en Massachusetts, EE. UU.',
            'Operación y gestión de grupos multiculturales 100% en inglés (C1), resolviendo bloqueos e incidentes en altura bajo presión mediante comunicación asertiva.',
          ],
          logo: '/logo-romaca.png',
          accentColor: '#7aad8f',
        },
        {
          id: 'icesi-admissions',
          period: 'Mar 2025 – May 2026',
          role: 'Monitor de Admisiones y Promoción Institucional',
          company: 'Universidad Icesi',
          location: 'Cali, Colombia',
          locationKind: 'Presencial',
          employmentType: 'Representación Institucional',
          shortDescription: 'Representación de Ingeniería de Sistemas en visitas vocacionales, ferias y eventos masivos institucionales.',
          bullets: [
            'Representación oficial de la carrera de Ingeniería de Sistemas en visitas a colegios, ferias vocacionales y eventos masivos como Icesi Interactiva y Open House.',
            'Presentaciones técnicas del plan de estudios y orientación a aspirantes, comunicando proyectos de software y metodologías ágiles a audiencias diversas.',
          ],
          logo: '/logo-icesi.png',
          accentColor: '#7c9eae',
        },
        {
          id: 'freelance-backend',
          period: 'Ago 2023 – Feb 2025',
          role: 'Desarrollador Backend & Algoritmos (Java)',
          company: 'Software Developer Freelance',
          location: 'Cali, Colombia',
          locationKind: 'Remoto',
          employmentType: 'Profesional Independiente',
          shortDescription: 'Desarrollo de lógica de backend, estructuras de datos avanzadas y optimización de código en Java.',
          bullets: [
            'Desarrollo de módulos de backend, optimización algorítmica y estructuras de datos avanzadas (grafos, árboles balanceados, colas de prioridad) en Java.',
            'Refactorización de código heredado y desarrollo de pruebas unitarias con JUnit, logrando 100% de cumplimiento en especificaciones de clientes independientes.',
          ],
          logo: '/logo-freelance.svg',
          accentColor: '#dcb991',
        },
      ],
    },
    education: {
      chip: 'Formación Académica',
      headlineFirst: 'Grado en Ingeniería de Sistemas &',
      headlineSecond: 'Distinciones de Honor',
      subtitle: 'Formación de alto rigor en diseño de software y sistemas distribuidos en la Universidad Icesi.',
      entry: {
        id: 'icesi-education',
        period: '2022 – Jul 2027 (Esperado)',
        current: true,
        degree: 'Grado en Ingeniería de Sistemas',
        institution: 'Universidad Icesi',
        location: 'Cali, Colombia',
        locationKind: 'Presencial',
        shortDescription: 'Formación universitaria de alto rigor en diseño de software, sistemas distribuidos y optimización algorítmica.',
        bullets: [
          'Promedio acumulado (GPA) de 4.4 / 5.0, reconocido con Beca por Excelencia Académica y permanencia ininterrumpida en la Lista de Honor institucional.',
          'Formación especializada con foco en Sistemas Distribuidos de alta concurrencia, Arquitectura de Software, Algoritmos Avanzados y Bases de Datos Relacionales.',
        ],
        gpa: '4.4',
        gpaScale: '5.0',
        honors: [
          'Beca por Excelencia Académica',
          'Permanencia continua en Lista de Honor institucional',
        ],
        description: 'Formación de alto rigor en diseño y construcción de sistemas computacionales complejos, arquitecturas distribuidas de alta concurrencia y optimización algorítmica. Rendimiento académico superior sostenido con reconocimiento institucional.',
        fundamentals: [
          'Sistemas Distribuidos',
          'Arquitectura de Software',
          'Algoritmos Avanzados',
          'Bases de Datos Relacionales',
        ],
        logo: '/logo-icesi.png',
        accentColor: '#7c9eae',
      },
    },
    techStack: {
      chip: 'Stack Tecnológico',
      headlineFirst: 'Herramientas &',
      headlineSecond: 'Tecnologías',
      subtitle: 'Stack técnico que utilizo para diseñar, construir y desplegar software en producción.',
      cards: [
        {
          id: 'frontend',
          title: 'Frontend & Mobile',
          badge: 'Client & UI',
          icon: 'layout',
          skills: [
            { name: 'Next.js 15', project: 'B2B Multi-Tenant SaaS · CRM Inmobiliario' },
            { name: 'React 19', project: 'Plataforma SaaS · HR Agile Analytics' },
            { name: 'TypeScript', project: 'Tipado estricto en frontend y backend' },
            { name: 'Tailwind CSS', project: 'Sistemas de diseño y componentes modulares' },
            { name: 'Flutter & Dart', project: 'Cross-Platform Mobile App (iOS / Android)' },
            { name: 'Framer Motion', project: 'Microinteracciones fluidas y transiciones' },
          ],
        },
        {
          id: 'backend',
          title: 'Backend & Sistemas',
          badge: 'Server & Logic',
          icon: 'server',
          skills: [
            { name: 'Java 11 / 17 / 21', project: 'Distributed Voting · Soluciones Algorítmicas' },
            { name: 'Spring Boot', project: 'Enterprise HR Agile Platform' },
            { name: 'ZeroC ICE (RPC)', project: 'High-Availability Distributed Voting' },
            { name: 'Python', project: 'Hybrid RAG & Búsqueda semántica' },
            { name: 'NestJS', project: 'Corporate Consulting Management' },
            { name: 'JUnit', project: 'Testing unitario y verificación de especificaciones' },
          ],
        },
        {
          id: 'cloud',
          title: 'Cloud & Bases de Datos',
          badge: 'Data & Infrastructure',
          icon: 'database',
          skills: [
            { name: 'PostgreSQL', project: 'B2B SaaS (Row Level Security) · CRM' },
            { name: 'Supabase', project: 'Autenticación, Storage y Postgres administrado' },
            { name: 'Docker', project: 'Contenerización de microservicios' },
            { name: 'Kubernetes', project: 'Resilient Microservices Pipeline' },
            { name: 'Jenkins CI/CD', project: 'Automatización de builds y despliegue continuo' },
            { name: 'Redis & Kafka', project: 'Caché distribuido y colas de eventos' },
          ],
        },
        {
          id: 'automation',
          title: 'Automatización & IA',
          badge: 'Workflows & APIs',
          icon: 'cpu',
          skills: [
            { name: 'n8n', project: 'Carolina Peña (+140 leads, ~16h/sem ahorradas)' },
            { name: 'Meta Graph API', project: 'Sincronización automatizada de inmuebles' },
            { name: 'pgvector', project: 'Búsqueda vectorial en catálogo académico (Icesi)' },
            { name: 'OpenAI API', project: 'Precalificación asistida y agentes RAG' },
            { name: 'REST & Webhooks', project: 'Integraciones desacopladas y servicios de terceros' },
          ],
        },
      ],
    },
    contact: {
      headlineFirst: '¿Buscando sumar talento?',
      headlineSecond: 'Hablemos.',
      subtitle:
        'Disponible para incorporarme a empresas y equipos de ingeniería que construyen productos escalables y valoran el rigor técnico.',
      primaryCtaText: 'Contactar por Correo',
      primaryCtaEmail: 'juandavidquintero49@gmail.com',
      githubUrl: 'https://github.com/Juanda2005123',
      linkedinUrl: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
      cvUrl: '/HV_JUAN_DAVID_QUINTERO_ES.pdf',
      cardName: 'Juan David Quintero',
      cardRole: 'Software Engineer',
      cardBadge: 'Disponible para contratación · Full-Time',
      cardCtaText: 'Descargar Hoja de Vida (PDF)',
      cardHighlights: [
        'Full-Stack & Backend: TypeScript, Next.js 15, Java 17/21, Spring Boot',
        'Computación distribuida, alta concurrencia y bases de datos relacionales',
        'Enfoque en arquitectura limpia, autonomía técnica y valor de negocio',
      ],
      rights: '© 2026 Juan David Quintero Peña · Cali, Colombia',
    },
    footer: {
      rights: 'Todos los derechos reservados.',
      tagline: 'Construido con Next.js, Tailwind CSS y Framer Motion.',
      backToTop: 'Volver arriba',
    },
  },
  en: {
    nav: {
      items: [
        { label: 'About', href: '#about' },
        { label: 'Projects', href: '#projects' },
        { label: 'Contact', href: '#contact' },
      ],
      contactCta: 'Contact',
    },
    hero: {
      greeting: "Hey, I'm",
      name: 'Juan David Quintero',
      headline: 'Software Engineer & Builder.',
      subtitle:
        'Transforming business problems into clean, modular, production-ready architectures.',
      badge: 'Software Engineer',
      primaryCta: {
        text: 'See Projects',
        targetId: 'projects',
      },
      secondaryCta: {
        text: 'Download CV',
        url: '/HV_JUAN_DAVID_QUINTERO_EN.pdf',
      },
      socials: [
        {
          name: 'LinkedIn',
          url: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
          icon: 'linkedin',
          ariaLabel: "Juan David Quintero's LinkedIn Profile",
        },
        {
          name: 'Email',
          url: 'mailto:juandavidquintero49@gmail.com',
          icon: 'email',
          ariaLabel: 'Send email to Juan David Quintero',
        },
      ],
      profileAlt: 'Juan David Quintero Peña at the Statue of Liberty, NYC',
      sidebarItems: [
        { icon: 'code', label: 'Software Engineer' },
        { icon: 'graduation', label: 'Icesi University' },
        { icon: 'map', label: 'Cali, Colombia' },
        { icon: 'typescript', label: 'TypeScript' },
        { icon: 'puzzle', label: 'Solving Complex Problems' },
        { icon: 'rocket', label: 'Building Scalable Apps' },
        { icon: 'brain', label: 'AI & Automation' },
      ],
      profileCardName: 'Juan David Quintero',
      profileCardRole: 'Software Engineer & Builder',
    },
    about: {
      title: 'About Me',
      manifestoParagraphs: [
        'I do not conceive software development as a mere transcription of requirements into code.',
        'My focus lies in deeply grasping the underlying business challenge, anticipating scalability bottlenecks, and engineering systems that eliminate operational friction.',
        'I specialize in the TypeScript ecosystem (Next.js 15, NestJS), backend in Java, and relational databases, embedding AI workflows only where they unlock tangible, measurable efficiency.',
      ],
    },
    featuredProjects: {
      chip: 'Featured Projects',
      headlineFirst: 'Architected for scale.',
      headlineSecond: 'Built for real-world impact.',
      subtitle:
        'Production architectures backed by proven scalability, multi-tenant isolation, and pragmatic AI automation.',
      links: {
        viewProject: 'Technical Specs',
        viewCode: 'Source Code',
        liveDemo: 'Live Demo',
      },
      projects: [
        {
          id: 'b2b-saas',
          category: 'ARCHITECTURE & SAAS',
          title: 'B2B Multi-Tenant SaaS Automation Platform',
          tagline:
            'Modular operational automation and enterprise management platform without code sprawl.',
          description:
            'Engineered to resolve integration variability in B2B enterprises. Implemented strict tenant isolation through dynamic middleware and PostgreSQL Row Level Security (RLS) policies. Structured Adapter and Strategy patterns to connect REST APIs through custom SFTP batches without touching core modules.',
          stack: ['Next.js 15', 'Supabase', 'PostgreSQL', 'Tailwind CSS', 'Adapter Pattern'],
          metric:
            '100% database-enforced multi-tenant isolation and modular deployments driven by JSONB config.',
          metricLabel: 'Production Impact',
          demoUrl: '#',
          githubUrl: '#',
        },
        {
          id: 'real-estate-crm',
          category: 'PRODUCTION PRODUCT & AI',
          title: 'Automated Real Estate & CRM Platform',
          tagline:
            'Comprehensive commercial solution with automated lead qualification and advertising sync.',
          description:
            'Development of public portal and internal CRM centralizing property listings and lead flows. Orchestrated conversational n8n agent for natural lead qualification (budget, location, payment method) before routing to human brokers, with AI-assisted creative generation and Meta Graph sync.',
          stack: ['Next.js 15', 'Supabase', 'n8n', 'Meta Graph API', 'AI Agents'],
          metric:
            '~16 hours saved weekly on manual qualification workflows and 140+ qualified leads processed.',
          metricLabel: 'Operational Efficiency',
          demoUrl: '#',
          githubUrl: '#',
        },
        {
          id: 'distributed-voting',
          category: 'DISTRIBUTED SYSTEMS & RESILIENCE',
          title: 'High-Availability Distributed Voting Infrastructure',
          tagline:
            'Fault-tolerant distributed architecture for high-concurrency secure ballot processing.',
          description:
            'Java 11 distributed infrastructure leveraging ZeroC ICE RPC middleware across independent institutional servers. Implemented Reliable Messaging pattern with transactional disk persistence and idempotent retry policies with unique UUIDs to prevent dropped or duplicate ballots during network splits.',
          stack: ['Java 11', 'ZeroC ICE', 'Reliable Messaging', 'Distributed Systems', 'JUnit'],
          metric:
            'Zero dropped ballots under stress testing of 100,000+ votes and automated self-healing after 30-second forced network partitions.',
          metricLabel: 'Fault Tolerance',
          demoUrl: '#',
          githubUrl: '#',
        },
        {
          id: 'intelligent-electives',
          category: 'APPLIED AI & HYBRID RETRIEVAL',
          title: 'Intelligent Electives Navigation Assistant',
          tagline:
            'Conversational search engine combining semantic retrieval and relational constraints for academic course catalogs.',
          description:
            'Engineered to overcome pure vector RAG degradation when evaluating hard constraints. Combines pgvector semantic embeddings with relational SQL filtering to satisfy complex student prompts cross-referencing subjective learning interests with strict schedule and prerequisite constraints across 120+ courses.',
          stack: ['Python', 'n8n', 'Supabase (pgvector)', 'Hybrid Search', 'LLMs'],
          metric:
            'Consistent deterministic accuracy on multi-variable queries (interest topic + schedule constraints).',
          metricLabel: 'Hybrid RAG Accuracy',
          demoUrl: '#',
          githubUrl: '#',
        },
      ],
    },
    otherProjects: {
      chip: 'More Work',
      headlineFirst: 'Additional',
      headlineSecond: 'Projects & Experiments',
      subtitle: 'A deeper dive into my portfolio of architectural solutions, algorithms, and applications.',
      projects: [
        {
          id: 'hr-agile-platform',
          category: 'Full-Stack & CI/CD',
          title: 'Enterprise HR Agile Platform',
          tagline: 'Plataforma colaborativa para optimización de flujos de reclutamiento y seguimiento de candidatos.',
          description: 'Sistema integral con backend en Spring Boot y frontend reactivo en Next.js. Diseñé tableros interactivos tipo Kanban para gestionar pipelines dinámicos de selección con autenticación basada en roles. Configuré la integración continua mediante pipelines automatizados en Jenkins para pruebas y despliegue.',
          stack: ['Spring Boot', 'Next.js', 'PostgreSQL', 'Jenkins', 'REST APIs', 'Docker'],
          impact: 'Liderazgo técnico como Scrum Master para un equipo de 8 ingenieros, reduciendo fricciones en entregas quincenales y automatizando pruebas de regresión.',
          image: 'https://images.unsplash.com/photo-1542626991-cbc4e32524cc?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Arquitectura',
          actionUrl: '#',
          actionSecondaryText: 'Repositorio GitHub',
          actionSecondaryUrl: '#',
        },
        {
          id: 'consulting-management',
          category: 'Enterprise Architecture',
          title: 'Corporate Consulting Management System',
          tagline: 'Plataforma centralizada para gestión contractual, presupuestal y seguimiento de consultorías institucionales.',
          description: 'Aplicación empresarial para digitalizar el ciclo de vida de consultorías de alto valor de la Universidad Icesi. Integré autenticación corporativa con Microsoft Azure AD y modelé permisos jerárquicos multi-nivel para coordinadores, consultores y líderes de proyecto.',
          stack: ['Next.js 15', 'NestJS', 'TypeScript', 'PostgreSQL', 'Azure AD'],
          impact: 'Trazabilidad integral en tiempo real de flujos de aprobación y contratos financieros, eliminando la dispersión de información en hojas de cálculo.',
          image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
          actionText: 'Caso de Estudio',
          actionUrl: '#',
          actionSecondaryText: 'Documentación Técnica',
          actionSecondaryUrl: '#',
        },
        {
          id: 'resilient-microservices',
          category: 'DevOps & Cloud Engineering',
          title: 'Resilient Microservices CI/CD Pipeline',
          tagline: 'Entorno orquestado de despliegue continuo y validación de carga para arquitecturas desacopladas.',
          description: 'Pipeline automatizado en Jenkins que gestiona el ciclo de vida de múltiples microservicios contenerizados con Docker. Implementé despliegues multi-namespace en Kubernetes y simulé escenarios de estrés concurrente y latencia mediante pruebas automatizadas con Locust.',
          stack: ['Docker', 'Kubernetes', 'Jenkins', 'Redis', 'Kafka', 'Locust', 'Linux'],
          impact: 'Automatización del 100% de los pasos de prueba y despliegue local, asegurando rollback ante fallos en tests de integración.',
          image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Configuración Docker/K8s',
          actionUrl: '#',
        },
        {
          id: 'dynamic-habits-insurtech',
          category: 'Fintech & Hackathon',
          title: 'Dynamic Habits-Based Insurance Engine',
          tagline: 'Prototipo funcional para cotización adaptativa de pólizas basado en perfilamiento de hábitos.',
          description: 'Motor de cálculo y plataforma interactiva desarrollada contrarreloj durante la competencia Global Hack 2025. Diseñé la lógica para procesar métricas de estilo de vida del usuario y ajustar dinámicamente las primas de seguros en tiempo real mediante interfaces ágiles.',
          stack: ['Next.js', 'Tailwind CSS', 'TypeScript', 'REST APIs'],
          impact: 'Reconocimiento Top 3 a nivel interinstitucional (Global Seguros & Design Factory Javeriana) entre decenas de propuestas.',
          image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Demo Conceptual',
          actionUrl: '#',
          actionSecondaryText: 'Resumen del Reto',
          actionSecondaryUrl: '#',
        },
        {
          id: 'cross-platform-mobile',
          category: 'Mobile Development',
          title: 'Cross-Platform Reactive Mobile App',
          tagline: 'Aplicación para dispositivos móviles con gestión reactiva de estado y componentes nativos.',
          description: 'Desarrollo de interfaces móviles fluidas y adaptativas para iOS y Android utilizando Flutter. Implementé patrones de arquitectura desacoplada para el consumo de endpoints REST y persistencia local de datos en caché offline.',
          stack: ['Flutter', 'Dart', 'REST APIs', 'SQLite', 'Hive'],
          impact: 'Arquitectura modular con cobertura de componentes reutilizables y sincronización asíncrona de datos.',
          image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Demo Móvil',
          actionUrl: '#',
          actionSecondaryText: 'Código Fuente',
          actionSecondaryUrl: '#',
        },
        {
          id: 'custom-algorithmic',
          category: 'Backend & Core Algorithms',
          title: 'Custom Algorithmic & Backend Solutions',
          tagline: 'Módulos de procesamiento algorítmico, lógica transaccional y optimización de estructuras de datos.',
          description: 'Desarrollo de soluciones a la medida para clientes independientes centradas en resolver problemas computacionales de alta complejidad. Incluye implementación y refactorización de grafos, árboles balanceados, colas de prioridad y optimización de consultas en Java.',
          stack: ['Java', 'JUnit', 'Algoritmos', 'Estructuras de datos avanzadas', 'Git'],
          impact: 'Reducción en tiempos de ejecución de algoritmos heredados y 100% de cumplimiento en especificaciones técnicas de clientes independientes.',
          image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=800&auto=format&fit=crop',
          actionText: 'Ver Ejemplos de Lógica',
          actionUrl: '#',
        }
      ]
    },
    workExperience: {
      chip: 'Work Experience',
      headlineFirst: 'Professional Career &',
      headlineSecond: 'Production Systems',
      subtitle: 'Track record in software engineering, system architecture, automation, and operational leadership.',
      entries: [
        {
          id: 'carolina-pena',
          period: 'Mar 2026 – Present',
          current: true,
          role: 'Full-Stack Software Engineer & Automation',
          company: 'Carolina Peña Inmobiliaria',
          location: 'Cali, Colombia',
          locationKind: 'Remote',
          employmentType: 'Independent Professional',
          shortDescription: 'Custom web portal and CRM built with Next.js 15 and Supabase, with listing sync and n8n pipelines.',
          bullets: [
            'End-to-end architecture and deployment of the custom real estate portal and CRM using Next.js 15 and PostgreSQL (Supabase).',
            'Automated listing syndication via Meta Graph API and conversational lead qualification via n8n, processing 140+ leads and saving ~16h/week.',
          ],
          logo: '/logo-carolina-pena-white.jpeg',
          accentColor: '#dcb991',
        },
        {
          id: 'camp-romaca',
          period: 'Jun 2026 – Aug 2026',
          role: 'High Ropes Instructor & Camp Counselor',
          company: 'Camp Romaca',
          location: 'Becket, MA, USA',
          locationKind: 'International',
          employmentType: 'International Immersion',
          shortDescription: 'Technical safety instruction and challenge course operations in a 100% English immersion setting.',
          bullets: [
            'Daily technical inspections and safety protocol enforcement across high ropes challenge courses under US regulations in Massachusetts.',
            'Multicultural group leadership in a 100% English setting (C1), resolving high-altitude incidents under pressure through assertive communication.',
          ],
          logo: '/logo-romaca.png',
          accentColor: '#7aad8f',
        },
        {
          id: 'icesi-admissions',
          period: 'Mar 2025 – May 2026',
          role: 'Admissions Monitor & Institutional Outreach',
          company: 'Universidad Icesi',
          location: 'Cali, Colombia',
          locationKind: 'On-site',
          employmentType: 'Institutional Representation',
          shortDescription: 'Department representation of Computer Engineering across high schools and large university events.',
          bullets: [
            'Official departmental representation of Computer Engineering across high schools, career fairs, and flagship showcases like Icesi Interactiva and Open House.',
            'Technical presentations of the engineering curriculum and prospective student advisement, translating software concepts to diverse audiences.',
          ],
          logo: '/logo-icesi.png',
          accentColor: '#7c9eae',
        },
        {
          id: 'freelance-backend',
          period: 'Aug 2023 – Feb 2025',
          role: 'Backend Developer & Algorithms (Java)',
          company: 'Software Developer Freelance',
          location: 'Cali, Colombia',
          locationKind: 'Remote',
          employmentType: 'Independent Professional',
          shortDescription: 'Backend logic, advanced data structures, and algorithmic optimization in Java.',
          bullets: [
            'Custom backend processing modules, transactional logic, and advanced data structures (balanced trees, graphs, priority queues) in Java.',
            'Legacy codebase refactoring and comprehensive JUnit test suite implementation, achieving 100% specification compliance for independent clients.',
          ],
          logo: '/logo-freelance.svg',
          accentColor: '#dcb991',
        },
      ],
    },
    education: {
      chip: 'Academic Background',
      headlineFirst: 'B.Sc. in Computer Engineering &',
      headlineSecond: 'Academic Honors',
      subtitle: 'Rigorous engineering training in software design and distributed systems at Universidad Icesi.',
      entry: {
        id: 'icesi-education',
        period: '2022 – Jul 2027 (Expected)',
        current: true,
        degree: 'B.Sc. in Computer Engineering',
        institution: 'Universidad Icesi',
        location: 'Cali, Colombia',
        locationKind: 'On-site',
        shortDescription: 'Rigorous computer engineering coursework focused on software architecture, distributed systems, and algorithmic optimization.',
        bullets: [
          'Cumulative GPA of 4.4 / 5.0, awarded the Academic Excellence Scholarship and continuous institutional Honor Roll standing.',
          'Specialized engineering coursework in high-concurrency Distributed Systems, Software Architecture, Advanced Algorithms, and Relational Databases.',
        ],
        gpa: '4.4',
        gpaScale: '5.0',
        honors: [
          'Academic Excellence Scholarship',
          'Continuous Institutional Honor Roll Standing',
        ],
        description: 'Rigorous engineering training focused on large-scale distributed computing, concurrent systems, and advanced algorithmic design. Proven sustained academic excellence recognized with institutional merit scholarships.',
        fundamentals: [
          'Distributed Systems',
          'Software Architecture',
          'Advanced Algorithms',
          'Relational Databases',
        ],
        logo: '/logo-icesi.png',
        accentColor: '#7c9eae',
      },
    },
    techStack: {
      chip: 'Tech Stack',
      headlineFirst: 'Tools &',
      headlineSecond: 'Technologies',
      subtitle: 'Core technologies I use to architect, build, and deploy production software.',
      cards: [
        {
          id: 'frontend',
          title: 'Frontend & Mobile',
          badge: 'Client & UI',
          icon: 'layout',
          skills: [
            { name: 'Next.js 15', project: 'B2B Multi-Tenant SaaS · Real Estate CRM' },
            { name: 'React 19', project: 'SaaS Platform · HR Agile Analytics' },
            { name: 'TypeScript', project: 'End-to-end strict typing across full stack' },
            { name: 'Tailwind CSS', project: 'Modular UI design systems and layouts' },
            { name: 'Flutter & Dart', project: 'Cross-Platform Mobile App (iOS / Android)' },
            { name: 'Framer Motion', project: 'Fluid micro-interactions and transitions' },
          ],
        },
        {
          id: 'backend',
          title: 'Backend & Systems',
          badge: 'Server & Logic',
          icon: 'server',
          skills: [
            { name: 'Java 11 / 17 / 21', project: 'Distributed Voting · Algorithmic Solutions' },
            { name: 'Spring Boot', project: 'Enterprise HR Agile Platform' },
            { name: 'ZeroC ICE (RPC)', project: 'High-Availability Distributed Voting' },
            { name: 'Python', project: 'Hybrid RAG & Semantic search engine' },
            { name: 'NestJS', project: 'Corporate Consulting Management' },
            { name: 'JUnit', project: 'Unit testing and spec verification' },
          ],
        },
        {
          id: 'cloud',
          title: 'Cloud & Databases',
          badge: 'Data & Infrastructure',
          icon: 'database',
          skills: [
            { name: 'PostgreSQL', project: 'B2B SaaS (Row Level Security) · CRM' },
            { name: 'Supabase', project: 'Auth, Storage, and managed Postgres' },
            { name: 'Docker', project: 'Microservices containerization' },
            { name: 'Kubernetes', project: 'Resilient Microservices Pipeline' },
            { name: 'Jenkins CI/CD', project: 'Automated build and delivery pipelines' },
            { name: 'Redis & Kafka', project: 'Distributed caching and event streams' },
          ],
        },
        {
          id: 'automation',
          title: 'Automation & AI',
          badge: 'Workflows & APIs',
          icon: 'cpu',
          skills: [
            { name: 'n8n', project: 'Carolina Peña (140+ leads, ~16h/week saved)' },
            { name: 'Meta Graph API', project: 'Automated real estate syndication' },
            { name: 'pgvector', project: 'Vector search in academic course catalog' },
            { name: 'OpenAI API', project: 'Lead prequalification & RAG agents' },
            { name: 'REST & Webhooks', project: 'Decoupled integrations & third-party APIs' },
          ],
        },
      ],
    },
    contact: {
      headlineFirst: 'Looking to hire engineering talent?',
      headlineSecond: "Let's talk.",
      subtitle:
        'Open to full-time software engineering roles in tech companies building scalable architectures and demanding technical excellence.',
      primaryCtaText: 'Get in touch via Email',
      primaryCtaEmail: 'juandavidquintero49@gmail.com',
      githubUrl: 'https://github.com/Juanda2005123',
      linkedinUrl: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
      cvUrl: '/HV_JUAN_DAVID_QUINTERO_EN.pdf',
      cardName: 'Juan David Quintero',
      cardRole: 'Software Engineer',
      cardBadge: 'Available for hire · Full-Time',
      cardCtaText: 'Download Resume / CV (PDF)',
      cardHighlights: [
        'Full-Stack & Backend: TypeScript, Next.js 15, Java 17/21, Spring Boot',
        'Distributed systems, high concurrency, and relational database design',
        'Demonstrated autonomy, clean code architecture, and high product velocity',
      ],
      rights: '© 2026 Juan David Quintero Peña · Cali, Colombia',
    },
    footer: {
      rights: 'All rights reserved.',
      tagline: 'Crafted with Next.js, Tailwind CSS, and Framer Motion.',
      backToTop: 'Back to top',
    },
  },
};

