import { PortfolioContent, Language } from './types';

export const portfolioData: Record<Language, PortfolioContent> = {
  es: {
    nav: {
      items: [
        { label: 'Sobre Mí', href: '#about' },
        { label: 'Proyectos', href: '#projects' },
        { label: 'Experiencia', href: '#experience' },
        { label: 'Educación', href: '#education' },
        { label: 'Habilidades', href: '#skills' },
        { label: 'Contacto', href: '#contact' },
      ],
      contactCta: 'Contacto',
    },
    hero: {
      greeting: 'Hola, soy',
      name: 'Juan David Quintero',
      headline: 'Ingeniero de Software & Creador.',
      subtitle:
        'Transformo problemas de negocio en arquitecturas limpias, modulares y listas para producción.',
      badge: 'Ingeniero de Software',
      primaryCta: {
        text: 'Ver Proyectos',
        targetId: 'projects',
      },
      secondaryCta: {
        text: 'Descargar CV',
        url: '/HV_JUAN_DAVID_QUINTERO_ES.pdf',
      },
      socials: [
        {
          name: 'LinkedIn',
          url: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
          icon: 'linkedin',
          ariaLabel: 'Perfil de LinkedIn de Juan David Quintero',
        },
        {
          name: 'Email',
          url: 'mailto:juandavidquintero0805@gmail.com',
          icon: 'email',
          ariaLabel: 'Enviar correo a Juan David Quintero',
        },
      ],
      profileAlt: 'Juan David Quintero Peña frente a la Estatua de la Libertad, NYC',
      sidebarItems: [
        { icon: 'code', label: 'Ingeniero de Software' },
        { icon: 'graduation', label: 'Universidad Icesi' },
        { icon: 'map', label: 'Cali, Colombia' },
        { icon: 'typescript', label: 'TypeScript' },
        { icon: 'puzzle', label: 'Resolución de Problemas Complejos' },
        { icon: 'rocket', label: 'Desarrollo de Apps Escalables' },
        { icon: 'brain', label: 'IA y Automatización' },
      ],
      profileCardName: 'Juan David Quintero',
      profileCardRole: 'Ingeniero de Software & Creador',
    },
    about: {
      title: 'Sobre Mí',
      manifestoParagraphs: [
        'Hoy la IA genera código en segundos; por eso veo mi valor no en teclear sintaxis, sino en entender el problema de fondo, analizar los datos y evaluar el impacto de cada decisión antes de construir.',
        'Me interesa tanto el diseño técnico como la coordinación para hacer realidad un proyecto: estructurar bases de datos limpias, aplicar IA donde realmente aporta valor y asegurar que el producto funcione de forma predecible para el usuario.',
        'Trabajar por un verano en Estados Unidos me enseñó que la técnica no basta: mantener la calma ante imprevistos, comunicarse con claridad en otro idioma y saber coordinar con un equipo es lo que realmente saca las cosas adelante.',
      ],
    },
    featuredProjects: {
      chip: 'Proyectos Destacados',
      headlineFirst: 'Arquitectura para escalar.',
      headlineSecond: 'Diseñada para impacto real.',
      subtitle:
        'Sistemas en producción respaldados por aislamiento estricto de datos, resiliencia distribuida y automatización pragmática con IA.',
      links: {
        viewProject: 'Detalles Técnicos',
        viewCode: 'Repositorio',
        liveDemo: 'Demo en Vivo',
      },
      projects: [
        {
          id: 'b2b-saas',
          category: 'ARQUITECTURA & SAAS',
          title: 'Plataforma SaaS B2B Multi-Tenant',
          tagline: '',
          description:
            'Diseñada para resolver integraciones empresariales heterogéneas sin fragmentar código base. Implementé resolución de inquilinos en el Edge con Next.js 15, aislamiento estricto mediante políticas RLS en PostgreSQL y patrones Adapter para admitir desde APIs REST hasta ingestas de archivos por lotes.',
          stack: ['Next.js 15', 'Supabase', 'PostgreSQL', 'Adapter Pattern', 'Tailwind CSS'],
          metric:
            'Aislamiento 100% verificado a nivel de base de datos y control modular vía configuración JSONB.',
          metricLabel: 'IMPACTO EN PRODUCCIÓN',
          demoUrl: '#',
          githubUrl: '#',
          image: '/project-b2b-saas-v3.jpg',
        },
        {
          id: 'real-estate-crm',
          category: 'PRODUCTO EN PRODUCCIÓN & IA',
          title: 'Plataforma Inmobiliaria & CRM Automatizado',
          tagline: '',
          description:
            'Solución comercial integral que centraliza el inventario inmobiliario y optimiza la adquisición de clientes. Desarrollé el portal público y un agente conversacional en n8n que precalifica prospectos en tiempo real, sincronizando publicaciones hacia la API de Meta.',
          stack: ['Next.js 15', 'Supabase', 'n8n', 'Meta Graph API', 'Agentes IA'],
          metric:
            'Ahorro de ~16h semanales en carga manual y más de 140 prospectos calificados procesados.',
          metricLabel: 'EFICIENCIA OPERATIVA',
          demoUrl: 'https://carolinapenainmobiliaria.com',
          githubUrl: '#',
          image: '/project-real-estate-v3.png',
        },
        {
          id: 'consulting-management',
          category: 'GOBERNANZA DE DATOS & B2B',
          title: 'Plataforma de Consultoría & Analítica B2B',
          tagline: '',
          description:
            'Plataforma de modernización comercial para el Centro de Consultoría de la Universidad Icesi. Diseñé una arquitectura modular con NestJS, Next.js y PostgreSQL (Prisma ORM) con Master Data Management (Golden Record) para erradicar la dispersión de datos, integrando modelos de clustering en Python y agentes de recomendación sobre flujos BPMN.',
          stack: ['NestJS', 'Next.js', 'PostgreSQL (Prisma)', 'Python (scikit-learn)', 'Docker'],
          metric:
            'Trazabilidad integral de una cartera histórica de +$14.915M COP (298 propuestas recuperadas) y consolidación de Golden Record institucional.',
          metricLabel: 'IMPACTO FINANCIERO & GOBERNANZA',
          demoUrl: '#',
          githubUrl: '#',
          image: '/project-consulting-management-v2.png',
        },
        {
          id: 'distributed-voting',
          category: 'SISTEMAS DISTRIBUIDOS',
          title: 'Infraestructura de Votación Distribuida',
          tagline: '',
          description:
            'Sistema distribuido tolerante a fallos desarrollado en Java 11 sobre middleware ZeroC ICE. Implementé el patrón Reliable Messaging con persistencia store-and-forward y reintentos idempotentes para garantizar cero pérdida ni duplicación de votos ante particiones de red.',
          stack: ['Java 11', 'ZeroC ICE', 'Reliable Messaging', 'Sistemas Distribuidos', 'JUnit'],
          metric:
            'Cero pérdidas en pruebas de estrés con +100.000 votos y recuperación automática ante caídas de red de 30s.',
          metricLabel: 'RESILIENCIA TÉCNICA',
          demoUrl: '#',
          githubUrl: '#',
          image: '/project-distributed-voting.jpg',
        },
      ],
    },
    otherProjects: {
      chip: 'Más Proyectos',
      headlineFirst: 'Otros',
      headlineSecond: 'Proyectos & Experimentos',
      subtitle: 'Explora una colección de soluciones innovadoras y arquitecturas adicionales en las que he trabajado.',
      projects: [
        {
          id: 'cross-platform-mobile',
          category: 'MOBILE DEVELOPMENT',
          title: 'Aplicación Móvil Reactiva Multiplataforma',
          tagline: '',
          description:
            'Aplicación móvil desarrollada en Flutter con arquitectura limpia y persistencia local offline. Diseñada para captura, georreferenciación y sincronización asíncrona de reportes con soporte nativo en iOS y Android.',
          stack: ['Flutter', 'Dart', 'REST APIs', 'SQLite'],
          impact: 'Rendimiento constante a 60 FPS con sincronización bidireccional tolerante a fallos de red.',
          image: '/project-mobile-app-v2.jpg',
          actionText: 'Ver Demo Móvil',
          actionUrl: '#',
          actionSecondaryText: 'Código Fuente',
          actionSecondaryUrl: '#',
        },
        {
          id: 'intelligent-electives',
          category: 'APPLIED AI & HYBRID SEARCH',
          title: 'Asistente Inteligente de Electivas',
          tagline: '',
          description:
            'Motor de consulta conversacional que combina búsqueda vectorial en pgvector con filtros relacionales en SQL. Permite consultar el catálogo académico cruzando intereses semánticos con restricciones duras de horarios y prerrequisitos.',
          stack: ['APIs', 'n8n', 'pgvector', 'Supabase'],
          impact: 'Cero alucinaciones en consultas multivariable con restricciones académicas estrictas.',
          image: '/project-electives-bot.png',
          actionText: 'Ver Detalles de Arquitectura',
          actionUrl: '#',
          actionSecondaryText: 'Repositorio GitHub',
          actionSecondaryUrl: '#',
        },
        {
          id: 'hr-agile-platform',
          category: 'FULL-STACK & CI/CD',
          title: 'Plataforma Ágil de Gestión de RRHH',
          tagline: '',
          description:
            'Sistema de reclutamiento y seguimiento de candidatos con tableros Kanban dinámicos y control de acceso RBAC. Lideré el equipo como Scrum Master y diseñé los pipelines de CI/CD en Jenkins para empaquetado y regresión continua.',
          stack: ['Spring Boot', 'Next.js', 'PostgreSQL', 'Jenkins'],
          impact: 'Liderazgo Scrum de 8 ingenieros y 100% de despliegues quincenales estables.',
          image: '/project-hr-agile.png',
          actionText: 'Ver Arquitectura',
          actionUrl: '#',
          actionSecondaryText: 'Repositorio GitHub',
          actionSecondaryUrl: '#',
        },
        {
          id: 'resilient-microservices',
          category: 'DEVOPS & CLOUD',
          title: 'Pipeline CI/CD para Microservicios',
          tagline: '',
          description:
            'Infraestructura automatizada en Jenkins para ciclo de vida de microservicios contenerizados. Implementé despliegues multi-namespace en Kubernetes y validación de tolerancia a fallos y latencia mediante pruebas de carga con Locust.',
          stack: ['Docker', 'Kubernetes', 'Jenkins', 'Locust'],
          impact: 'Automatización total de integración continua con reversión (rollback) ante fallos.',
          image: '/project-resilient-microservices-v3.png',
          actionText: 'Ver Configuración Docker/K8s',
          actionUrl: '#',
        },
      ]
    },
    workExperience: {
      chip: 'Experiencia Laboral',
      headlineFirst: 'Trayectoria Profesional &',
      headlineSecond: 'Roles en Producción',
      subtitle: 'Historial de desarrollo de software, arquitectura de sistemas, automatización y liderazgo operativo.',
      entries: [
        {
          id: 'carolina-pena',
          period: 'Mar 2026 – Presente',
          current: true,
          role: 'Ingeniero de Software Full-Stack & Automatización',
          company: 'Carolina Peña Inmobiliaria',
          location: 'Cali, Colombia',
          locationKind: 'Remoto',
          employmentType: 'Profesional Independiente',
          shortDescription: 'Desarrollo de plataforma web y CRM a medida con Next.js 15 y Supabase, con sincronización publicitaria y flujos en n8n.',
          bullets: [
            'Diseño e implementación de la arquitectura completa del portal inmobiliario y CRM a medida sobre Next.js 15 y PostgreSQL (Supabase).',
            'Automatización de publicaciones mediante Meta Graph API y flujo de calificación de prospectos con n8n, procesando +140 leads y ahorrando ~16h/semana de gestión manual.',
          ],
          logo: '/logo-carolina-pena-white.jpeg',
          accentColor: '#dcb991',
        },
        {
          id: 'camp-romaca',
          period: 'Jun 2026 – Ago 2026',
          role: 'Instructor de Cuerdas Altas & Consejero de Campamento',
          company: 'Camp Romaca',
          location: 'Becket, MA, EE. UU.',
          locationKind: 'Internacional',
          employmentType: 'Inmersión Internacional',
          shortDescription: 'Instrucción técnica y liderazgo de seguridad en circuitos de cuerdas altas en entorno 100% en inglés.',
          bullets: [
            'Inspección técnica diaria y control de protocolos de seguridad en circuitos de cuerdas altas bajo normativa internacional en Massachusetts, EE. UU.',
            'Operación y gestión de grupos multiculturales 100% en inglés (C1), resolviendo bloqueos e incidentes en altura bajo presión mediante comunicación asertiva.',
          ],
          logo: '/logo-romaca.png',
          accentColor: '#7aad8f',
        },
        {
          id: 'icesi-admissions',
          period: 'Mar 2025 – May 2026',
          role: 'Monitor de Admisiones y Promoción Institucional',
          company: 'Universidad Icesi',
          location: 'Cali, Colombia',
          locationKind: 'Presencial',
          employmentType: 'Representación Institucional',
          shortDescription: 'Representación de Ingeniería de Sistemas en visitas vocacionales, ferias y eventos masivos institucionales.',
          bullets: [
            'Representación oficial de la carrera de Ingeniería de Sistemas en visitas a colegios, ferias vocacionales y eventos masivos como Icesi Interactiva y Open House.',
            'Presentaciones técnicas del plan de estudios y orientación a aspirantes, comunicando proyectos de software y metodologías ágiles a audiencias diversas.',
          ],
          logo: '/logo-icesi.png',
          accentColor: '#7c9eae',
        },
        {
          id: 'freelance-backend',
          period: 'Ago 2023 – Feb 2025',
          role: 'Desarrollador Backend & Algoritmos (Java)',
          company: 'Desarrollador de Software Independiente',
          location: 'Cali, Colombia',
          locationKind: 'Remoto',
          employmentType: 'Profesional Independiente',
          shortDescription: 'Desarrollo de lógica de backend, estructuras de datos avanzadas y optimización de código en Java.',
          bullets: [
            'Desarrollo de módulos de backend, optimización algorítmica y estructuras de datos avanzadas (grafos, árboles balanceados, colas de prioridad) en Java.',
            'Refactorización de código heredado y desarrollo de pruebas unitarias con JUnit, logrando 100% de cumplimiento en especificaciones de clientes independientes.',
          ],
          logo: '/logo-freelance.svg',
          accentColor: '#dcb991',
        },
      ],
    },
    education: {
      chip: 'Formación Académica',
      headlineFirst: 'Grado en Ingeniería de Sistemas &',
      headlineSecond: 'Distinciones de Honor',
      subtitle: 'Formación de alto rigor en diseño de software y sistemas distribuidos en la Universidad Icesi.',
      entry: {
        id: 'icesi-education',
        period: '2022 – Jul 2027 (Esperado)',
        current: true,
        degree: 'Grado en Ingeniería de Sistemas',
        institution: 'Universidad Icesi',
        location: 'Cali, Colombia',
        locationKind: 'Presencial',
        shortDescription: 'Formación universitaria de alto rigor en diseño de software, sistemas distribuidos y optimización algorítmica.',
        bullets: [
          'Promedio acumulado (GPA) de 4.4 / 5.0, reconocido con Beca por Excelencia Académica y permanencia ininterrumpida en la Lista de Honor institucional.',
          'Formación especializada con foco en Sistemas Distribuidos de alta concurrencia, Arquitectura de Software, Algoritmos Avanzados y Bases de Datos Relacionales.',
        ],
        gpa: '4.4',
        gpaScale: '5.0',
        honors: [
          'Beca por Excelencia Académica',
          'Permanencia continua en Lista de Honor institucional',
        ],
        description: 'Formación de alto rigor en diseño y construcción de sistemas computacionales complejos, arquitecturas distribuidas de alta concurrencia y optimización algorítmica. Rendimiento académico superior sostenido con reconocimiento institucional.',
        fundamentals: [
          'Sistemas Distribuidos',
          'Arquitectura de Software',
          'Algoritmos Avanzados',
          'Bases de Datos Relacionales',
        ],
        logo: '/logo-icesi.png',
        accentColor: '#7c9eae',
      },
    },
    techStack: {
      chip: 'Stack Tecnológico',
      headlineFirst: 'Herramientas &',
      headlineSecond: 'Tecnologías',
      subtitle: 'Stack técnico que utilizo para diseñar, construir y desplegar software en producción.',
      cards: [
        {
          id: 'frontend',
          title: 'Frontend & Mobile',
          badge: 'Client & UI',
          icon: 'layout',
          skills: [
            { name: 'Next.js 15', project: 'B2B Multi-Tenant SaaS · CRM Inmobiliario' },
            { name: 'React 19', project: 'Plataforma SaaS · HR Agile Analytics' },
            { name: 'TypeScript', project: 'Tipado estricto en frontend y backend' },
            { name: 'Tailwind CSS', project: 'Sistemas de diseño y componentes modulares' },
            { name: 'Flutter & Dart', project: 'Cross-Platform Mobile App (iOS / Android)' },
            { name: 'Framer Motion', project: 'Microinteracciones fluidas y transiciones' },
          ],
        },
        {
          id: 'backend',
          title: 'Backend & Sistemas',
          badge: 'Server & Logic',
          icon: 'server',
          skills: [
            { name: 'Java 11 / 17 / 21', project: 'Distributed Voting · Soluciones Algorítmicas' },
            { name: 'Spring Boot', project: 'Enterprise HR Agile Platform' },
            { name: 'ZeroC ICE (RPC)', project: 'High-Availability Distributed Voting' },
            { name: 'Python', project: 'Hybrid RAG & Búsqueda semántica' },
            { name: 'NestJS', project: 'Corporate Consulting Management' },
            { name: 'JUnit', project: 'Testing unitario y verificación de especificaciones' },
          ],
        },
        {
          id: 'cloud',
          title: 'Cloud & Bases de Datos',
          badge: 'Data & Infrastructure',
          icon: 'database',
          skills: [
            { name: 'PostgreSQL', project: 'B2B SaaS (Row Level Security) · CRM' },
            { name: 'Supabase', project: 'Autenticación, Storage y Postgres administrado' },
            { name: 'Docker', project: 'Contenerización de microservicios' },
            { name: 'Kubernetes', project: 'Resilient Microservices Pipeline' },
            { name: 'Jenkins CI/CD', project: 'Automatización de builds y despliegue continuo' },
            { name: 'Redis & Kafka', project: 'Caché distribuido y colas de eventos' },
          ],
        },
        {
          id: 'automation',
          title: 'Automatización & IA',
          badge: 'Workflows & APIs',
          icon: 'cpu',
          skills: [
            { name: 'n8n', project: 'Carolina Peña (+140 leads, ~16h/sem ahorradas)' },
            { name: 'Meta Graph API', project: 'Sincronización automatizada de inmuebles' },
            { name: 'pgvector', project: 'Búsqueda vectorial en catálogo académico (Icesi)' },
            { name: 'OpenAI API', project: 'Precalificación asistida y agentes RAG' },
            { name: 'REST & Webhooks', project: 'Integraciones desacopladas y servicios de terceros' },
          ],
        },
      ],
    },
    contact: {
      headlineFirst: '¿Buscando sumar talento?',
      headlineSecond: 'Hablemos.',
      subtitle:
        'Disponible para incorporarme a empresas y equipos de ingeniería que construyen productos escalables y valoran el rigor técnico.',
      primaryCtaText: 'Contactar por Correo',
      primaryCtaEmail: 'juandavidquintero0805@gmail.com',
      githubUrl: 'https://github.com/Juanda2005123',
      linkedinUrl: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
      cvUrl: '/HV_JUAN_DAVID_QUINTERO_ES.pdf',
      cardName: 'Juan David Quintero',
      cardRole: 'Ingeniero de Software',
      cardBadge: 'Disponible para contratación · Full-Time',
      cardCtaText: 'Descargar Hoja de Vida (PDF)',
      cardHighlights: [
        'Full-Stack & Backend: TypeScript, Next.js 15, Java 17/21, Spring Boot',
        'Computación distribuida, alta concurrencia y bases de datos relacionales',
        'Enfoque en arquitectura limpia, autonomía técnica y valor de negocio',
      ],
      rights: '© 2026 Juan David Quintero Peña · Cali, Colombia',
    },
    footer: {
      rights: 'Todos los derechos reservados.',
      tagline: 'Construido con Next.js, Tailwind CSS y Framer Motion.',
      backToTop: 'Volver arriba',
    },
  },
  en: {
    nav: {
      items: [
        { label: 'About', href: '#about' },
        { label: 'Projects', href: '#projects' },
        { label: 'Experience', href: '#experience' },
        { label: 'Education', href: '#education' },
        { label: 'Skills', href: '#skills' },
        { label: 'Contact', href: '#contact' },
      ],
      contactCta: 'Contact',
    },
    hero: {
      greeting: "Hey, I'm",
      name: 'Juan David Quintero',
      headline: 'Software Engineer & Builder.',
      subtitle:
        'Transforming business problems into clean, modular, production-ready architectures.',
      badge: 'Software Engineer',
      primaryCta: {
        text: 'See Projects',
        targetId: 'projects',
      },
      secondaryCta: {
        text: 'Download CV',
        url: '/HV_JUAN_DAVID_QUINTERO_EN.pdf',
      },
      socials: [
        {
          name: 'LinkedIn',
          url: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
          icon: 'linkedin',
          ariaLabel: "Juan David Quintero's LinkedIn Profile",
        },
        {
          name: 'Email',
          url: 'mailto:juandavidquintero0805@gmail.com',
          icon: 'email',
          ariaLabel: 'Send email to Juan David Quintero',
        },
      ],
      profileAlt: 'Juan David Quintero Peña at the Statue of Liberty, NYC',
      sidebarItems: [
        { icon: 'code', label: 'Software Engineer' },
        { icon: 'graduation', label: 'Icesi University' },
        { icon: 'map', label: 'Cali, Colombia' },
        { icon: 'typescript', label: 'TypeScript' },
        { icon: 'puzzle', label: 'Solving Complex Problems' },
        { icon: 'rocket', label: 'Building Scalable Apps' },
        { icon: 'brain', label: 'AI & Automation' },
      ],
      profileCardName: 'Juan David Quintero',
      profileCardRole: 'Software Engineer & Builder',
    },
    about: {
      title: 'About Me',
      manifestoParagraphs: [
        'Today AI generates code in seconds; that is why I see my value not in typing syntax, but in understanding the root problem, analyzing data, and assessing the impact of each decision before building.',
        'I care deeply about both technical architecture and project execution: designing clean relational schemas, applying AI where it truly drives value, and ensuring products behave predictably for end users.',
        'Spending a summer working in the United States taught me that technical skills alone aren\'t enough. Staying calm under pressure, communicating clearly in another language, and coordinating across teams are the skills that actually drive results.',
      ],
    },
    featuredProjects: {
      chip: 'Featured Projects',
      headlineFirst: 'Architected for scale.',
      headlineSecond: 'Built for real-world impact.',
      subtitle:
        'Production architectures backed by proven scalability, multi-tenant isolation, and pragmatic AI automation.',
      links: {
        viewProject: 'Technical Specs',
        viewCode: 'Source Code',
        liveDemo: 'Live Demo',
      },
      projects: [
        {
          id: 'b2b-saas',
          category: 'ARCHITECTURE & SAAS',
          title: 'B2B Multi-Tenant SaaS Platform',
          tagline: '',
          description:
            'Engineered to handle heterogeneous enterprise integrations without codebase fragmentation. Features tenant resolution at the Edge with Next.js 15, database-level isolation via PostgreSQL RLS, and Adapter patterns for dynamic REST and batch ingestion.',
          stack: ['Next.js 15', 'Supabase', 'PostgreSQL', 'Adapter Pattern', 'Tailwind CSS'],
          metric:
            '100% database-level isolation verified and modular control via JSONB configuration.',
          metricLabel: 'PRODUCTION IMPACT',
          demoUrl: '#',
          githubUrl: '#',
          image: '/project-b2b-saas-v3.jpg',
        },
        {
          id: 'real-estate-crm',
          category: 'PRODUCTION PRODUCT & AI',
          title: 'Real Estate Platform & AI Automation CRM',
          tagline: '',
          description:
            'End-to-end commercial platform centralizing property inventory and lead acquisition. Built the public portal and an n8n conversational agent that pre-qualifies prospects in real-time while automating campaign sync via Meta Graph API.',
          stack: ['Next.js 15', 'Supabase', 'n8n', 'Meta Graph API', 'Agentes IA'],
          metric:
            '~16h/week saved on manual workload with over 140 qualified prospects automatically processed.',
          metricLabel: 'OPERATIONAL EFFICIENCY',
          demoUrl: 'https://carolinapenainmobiliaria.com',
          githubUrl: '#',
          image: '/project-real-estate-v3.png',
        },
        {
          id: 'consulting-management',
          category: 'DATA GOVERNANCE & B2B ARCHITECTURE',
          title: 'B2B Consulting Governance & Analytics Platform',
          tagline: '',
          description:
            'Enterprise modernization platform for Universidad Icesi\'s Consulting Center. Architected a modular system with NestJS, Next.js, and PostgreSQL (Prisma ORM) featuring Master Data Management (Golden Record) to eliminate data fragmentation, integrating Python clustering and AI recommendation agents across BPMN-standardized pipelines.',
          stack: ['NestJS', 'Next.js', 'PostgreSQL (Prisma)', 'Python (scikit-learn)', 'Docker'],
          metric:
            'Full lifecycle governance over +$14.9B COP historical pipeline (298 stalled proposals recovered) and institutional Golden Record consolidation.',
          metricLabel: 'FINANCIAL IMPACT & GOVERNANCE',
          demoUrl: '#',
          githubUrl: '#',
          image: '/project-consulting-management-v2.png',
        },
        {
          id: 'distributed-voting',
          category: 'DISTRIBUTED SYSTEMS',
          title: 'High-Availability Distributed Voting System',
          tagline: '',
          description:
            'Fault-tolerant distributed infrastructure built in Java 11 over ZeroC ICE RPC middleware. Implemented the Reliable Messaging pattern with store-and-forward persistence and idempotent retries to guarantee zero vote loss across network partitions.',
          stack: ['Java 11', 'ZeroC ICE', 'Reliable Messaging', 'Sistemas Distribuidos', 'JUnit'],
          metric:
            'Zero vote loss under stress tests with +100,000 votes and automatic recovery from 30s network outages.',
          metricLabel: 'FAULT TOLERANCE',
          demoUrl: '#',
          githubUrl: '#',
          image: '/project-distributed-voting.jpg',
        },
      ],
    },
    otherProjects: {
      chip: 'More Work',
      headlineFirst: 'Additional',
      headlineSecond: 'Projects & Experiments',
      subtitle: 'A deeper dive into my portfolio of architectural solutions, algorithms, and applications.',
      projects: [
        {
          id: 'cross-platform-mobile',
          category: 'MOBILE DEVELOPMENT',
          title: 'Cross-Platform Reactive Mobile App',
          tagline: '',
          description:
            'Clean architecture mobile application built in Flutter with offline local persistence. Designed for capturing, geo-referencing, and asynchronously syncing incident reports with native iOS and Android performance.',
          stack: ['Flutter', 'Dart', 'REST APIs', 'SQLite'],
          impact: '60 FPS fluid rendering with network fault-tolerant bidirectional data sync.',
          image: '/project-mobile-app-v2.jpg',
          actionText: 'View Mobile Demo',
          actionUrl: '#',
          actionSecondaryText: 'Source Code',
          actionSecondaryUrl: '#',
        },
        {
          id: 'intelligent-electives',
          category: 'APPLIED AI & HYBRID SEARCH',
          title: 'Intelligent Electives Navigator',
          tagline: '',
          description:
            'Conversational search engine pairing pgvector semantic retrieval with hard relational SQL filtering. Enables students to query course catalogs by matching topics of interest with rigid schedule and prerequisite constraints.',
          stack: ['APIs', 'n8n', 'pgvector', 'Supabase'],
          impact: 'Deterministic accuracy on multi-variable academic queries under hard schedule constraints.',
          image: '/project-electives-bot.png',
          actionText: 'View Architecture',
          actionUrl: '#',
          actionSecondaryText: 'GitHub Repository',
          actionSecondaryUrl: '#',
        },
        {
          id: 'hr-agile-platform',
          category: 'FULL-STACK & CI/CD',
          title: 'Enterprise HR Agile Platform',
          tagline: '',
          description:
            'Recruitment and applicant tracking system featuring dynamic Kanban workflows and RBAC security. Served as Scrum Master leading an 8-engineer team and configured automated Jenkins CI/CD test pipelines.',
          stack: ['Spring Boot', 'Next.js', 'PostgreSQL', 'Jenkins'],
          impact: 'Agile leadership of 8 engineers with 100% stable bi-weekly automated deployments.',
          image: '/project-hr-agile.png',
          actionText: 'View Architecture',
          actionUrl: '#',
          actionSecondaryText: 'GitHub Repository',
          actionSecondaryUrl: '#',
        },
        {
          id: 'resilient-microservices',
          category: 'DEVOPS & CLOUD',
          title: 'Resilient Microservices CI/CD Pipeline',
          tagline: '',
          description:
            'Automated Jenkins infrastructure managing the lifecycle of containerized microservices. Implemented multi-namespace Kubernetes deployments and latency resilience validation using Locust load-testing suites.',
          stack: ['Docker', 'Kubernetes', 'Jenkins', 'Locust'],
          impact: 'End-to-end automated testing and deployment with instant rollback mechanisms.',
          image: '/project-resilient-microservices-v3.png',
          actionText: 'View Docker/K8s Config',
          actionUrl: '#',
        },
      ]
    },
    workExperience: {
      chip: 'Work Experience',
      headlineFirst: 'Professional Career &',
      headlineSecond: 'Production Systems',
      subtitle: 'Track record in software engineering, system architecture, automation, and operational leadership.',
      entries: [
        {
          id: 'carolina-pena',
          period: 'Mar 2026 – Present',
          current: true,
          role: 'Full-Stack Software Engineer & Automation',
          company: 'Carolina Peña Inmobiliaria',
          location: 'Cali, Colombia',
          locationKind: 'Remote',
          employmentType: 'Independent Professional',
          shortDescription: 'Custom web portal and CRM built with Next.js 15 and Supabase, with listing sync and n8n pipelines.',
          bullets: [
            'End-to-end architecture and deployment of the custom real estate portal and CRM using Next.js 15 and PostgreSQL (Supabase).',
            'Automated listing syndication via Meta Graph API and conversational lead qualification via n8n, processing 140+ leads and saving ~16h/week.',
          ],
          logo: '/logo-carolina-pena-white.jpeg',
          accentColor: '#dcb991',
        },
        {
          id: 'camp-romaca',
          period: 'Jun 2026 – Aug 2026',
          role: 'High Ropes Instructor & Camp Counselor',
          company: 'Camp Romaca',
          location: 'Becket, MA, USA',
          locationKind: 'International',
          employmentType: 'International Immersion',
          shortDescription: 'Technical safety instruction and challenge course operations in a 100% English immersion setting.',
          bullets: [
            'Daily technical inspections and safety protocol enforcement across high ropes challenge courses under US regulations in Massachusetts.',
            'Multicultural group leadership in a 100% English setting (C1), resolving high-altitude incidents under pressure through assertive communication.',
          ],
          logo: '/logo-romaca.png',
          accentColor: '#7aad8f',
        },
        {
          id: 'icesi-admissions',
          period: 'Mar 2025 – May 2026',
          role: 'Admissions Monitor & Institutional Outreach',
          company: 'Universidad Icesi',
          location: 'Cali, Colombia',
          locationKind: 'On-site',
          employmentType: 'Institutional Representation',
          shortDescription: 'Department representation of Computer Engineering across high schools and large university events.',
          bullets: [
            'Official departmental representation of Computer Engineering across high schools, career fairs, and flagship showcases like Icesi Interactiva and Open House.',
            'Technical presentations of the engineering curriculum and prospective student advisement, translating software concepts to diverse audiences.',
          ],
          logo: '/logo-icesi.png',
          accentColor: '#7c9eae',
        },
        {
          id: 'freelance-backend',
          period: 'Aug 2023 – Feb 2025',
          role: 'Backend Developer & Algorithms (Java)',
          company: 'Software Developer Freelance',
          location: 'Cali, Colombia',
          locationKind: 'Remote',
          employmentType: 'Independent Professional',
          shortDescription: 'Backend logic, advanced data structures, and algorithmic optimization in Java.',
          bullets: [
            'Custom backend processing modules, transactional logic, and advanced data structures (balanced trees, graphs, priority queues) in Java.',
            'Legacy codebase refactoring and comprehensive JUnit test suite implementation, achieving 100% specification compliance for independent clients.',
          ],
          logo: '/logo-freelance.svg',
          accentColor: '#dcb991',
        },
      ],
    },
    education: {
      chip: 'Academic Background',
      headlineFirst: 'B.Sc. in Computer Engineering &',
      headlineSecond: 'Academic Honors',
      subtitle: 'Rigorous engineering training in software design and distributed systems at Universidad Icesi.',
      entry: {
        id: 'icesi-education',
        period: '2022 – Jul 2027 (Expected)',
        current: true,
        degree: 'B.Sc. in Computer Engineering',
        institution: 'Universidad Icesi',
        location: 'Cali, Colombia',
        locationKind: 'On-site',
        shortDescription: 'Rigorous computer engineering coursework focused on software architecture, distributed systems, and algorithmic optimization.',
        bullets: [
          'Cumulative GPA of 4.4 / 5.0, awarded the Academic Excellence Scholarship and continuous institutional Honor Roll standing.',
          'Specialized engineering coursework in high-concurrency Distributed Systems, Software Architecture, Advanced Algorithms, and Relational Databases.',
        ],
        gpa: '4.4',
        gpaScale: '5.0',
        honors: [
          'Academic Excellence Scholarship',
          'Continuous Institutional Honor Roll Standing',
        ],
        description: 'Rigorous engineering training focused on large-scale distributed computing, concurrent systems, and advanced algorithmic design. Proven sustained academic excellence recognized with institutional merit scholarships.',
        fundamentals: [
          'Distributed Systems',
          'Software Architecture',
          'Advanced Algorithms',
          'Relational Databases',
        ],
        logo: '/logo-icesi.png',
        accentColor: '#7c9eae',
      },
    },
    techStack: {
      chip: 'Tech Stack',
      headlineFirst: 'Tools &',
      headlineSecond: 'Technologies',
      subtitle: 'Core technologies I use to architect, build, and deploy production software.',
      cards: [
        {
          id: 'frontend',
          title: 'Frontend & Mobile',
          badge: 'Client & UI',
          icon: 'layout',
          skills: [
            { name: 'Next.js 15', project: 'B2B Multi-Tenant SaaS · Real Estate CRM' },
            { name: 'React 19', project: 'SaaS Platform · HR Agile Analytics' },
            { name: 'TypeScript', project: 'End-to-end strict typing across full stack' },
            { name: 'Tailwind CSS', project: 'Modular UI design systems and layouts' },
            { name: 'Flutter & Dart', project: 'Cross-Platform Mobile App (iOS / Android)' },
            { name: 'Framer Motion', project: 'Fluid micro-interactions and transitions' },
          ],
        },
        {
          id: 'backend',
          title: 'Backend & Systems',
          badge: 'Server & Logic',
          icon: 'server',
          skills: [
            { name: 'Java 11 / 17 / 21', project: 'Distributed Voting · Algorithmic Solutions' },
            { name: 'Spring Boot', project: 'Enterprise HR Agile Platform' },
            { name: 'ZeroC ICE (RPC)', project: 'High-Availability Distributed Voting' },
            { name: 'Python', project: 'Hybrid RAG & Semantic search engine' },
            { name: 'NestJS', project: 'Corporate Consulting Management' },
            { name: 'JUnit', project: 'Unit testing and spec verification' },
          ],
        },
        {
          id: 'cloud',
          title: 'Cloud & Databases',
          badge: 'Data & Infrastructure',
          icon: 'database',
          skills: [
            { name: 'PostgreSQL', project: 'B2B SaaS (Row Level Security) · CRM' },
            { name: 'Supabase', project: 'Auth, Storage, and managed Postgres' },
            { name: 'Docker', project: 'Microservices containerization' },
            { name: 'Kubernetes', project: 'Resilient Microservices Pipeline' },
            { name: 'Jenkins CI/CD', project: 'Automated build and delivery pipelines' },
            { name: 'Redis & Kafka', project: 'Distributed caching and event streams' },
          ],
        },
        {
          id: 'automation',
          title: 'Automation & AI',
          badge: 'Workflows & APIs',
          icon: 'cpu',
          skills: [
            { name: 'n8n', project: 'Carolina Peña (140+ leads, ~16h/week saved)' },
            { name: 'Meta Graph API', project: 'Automated real estate syndication' },
            { name: 'pgvector', project: 'Vector search in academic course catalog' },
            { name: 'OpenAI API', project: 'Lead prequalification & RAG agents' },
            { name: 'REST & Webhooks', project: 'Decoupled integrations & third-party APIs' },
          ],
        },
      ],
    },
    contact: {
      headlineFirst: 'Looking to hire engineering talent?',
      headlineSecond: "Let's talk.",
      subtitle:
        'Open to full-time software engineering roles in tech companies building scalable architectures and demanding technical excellence.',
      primaryCtaText: 'Get in touch via Email',
      primaryCtaEmail: 'juandavidquintero0805@gmail.com',
      githubUrl: 'https://github.com/Juanda2005123',
      linkedinUrl: 'https://www.linkedin.com/in/juan-david-quintero-software-engineer-full-stack-automation-ai/',
      cvUrl: '/HV_JUAN_DAVID_QUINTERO_EN.pdf',
      cardName: 'Juan David Quintero',
      cardRole: 'Software Engineer',
      cardBadge: 'Available for hire · Full-Time',
      cardCtaText: 'Download Resume / CV (PDF)',
      cardHighlights: [
        'Full-Stack & Backend: TypeScript, Next.js 15, Java 17/21, Spring Boot',
        'Distributed systems, high concurrency, and relational database design',
        'Demonstrated autonomy, clean code architecture, and high product velocity',
      ],
      rights: '© 2026 Juan David Quintero Peña · Cali, Colombia',
    },
    footer: {
      rights: 'All rights reserved.',
      tagline: 'Crafted with Next.js, Tailwind CSS, and Framer Motion.',
      backToTop: 'Back to top',
    },
  },
};

